select max(biz_date) from ftuser.FUND_ANALYSIS_INFO
select max(biz_date) from ftuser.FUND_ASSET_STRUCTUR
select max(biz_date) from ftuser.FUND_BOND_CONCEPT
select max(biz_date) from ftuser.FUND_BOND_POSITION
select max(biz_date) from ftuser.FUND_EQ_BRINSON_DETAIL
select max(biz_date) from ftuser.FUND_EQ_BRINSON_SUM
select max(biz_date) from ftuser.FUND_EQ_INDUSTRY
select max(biz_date) from ftuser.FUND_EQ_POSITION
select max(biz_date) from ftuser.FUND_EQ_STYLE
select max(biz_date) from ftuser.FUND_FUND_POSITION
select max(biz_date) from ftuser.FUND_FUT_POSITION
select max(biz_date) from ftuser.FUND_FUT_TYPE
select max(biz_date) from ftuser.FUND_QUANT_ANALYSIS
select max(biz_date) from ftuser.FUND_RETURN_DETAIL
select max(biz_date) from ftuser.FUND_VAR
select max(biz_date) from ftuser.ORIG_FUND_SUMMARY
select max(biz_date) from ftuser.ORIG_POSITION