select count(*) from wind.ASHARECALENDAR
select count(*) from wind.ASHAREDESCRIPTION
select count(*) from wind.AINDEXDESCRIPTION
select count(*) from wind.ASHAREINDUSTRIESCODE
select count(*) from wind.ASHARESWINDUSTRIESCLASS
select count(*) from wind.ASHARECONSEPTION
select count(*) from wind.CFUTURESDESCRIPTION
select count(*) from wind.CFUTURESCONTPRO
select count(*) from wind.HKEXCALENDAR
select count(*) from wind.HKSHAREDESCRIPTION
select count(*) from wind.HKSTOCKHSINDUSTRIESMEMBERS
select count(*) from wind.HKSTOCKINDUSTRIESCODE
select count(*) from wind.CBONDDESCRIPTION
select count(*) from wind.CBONDINDUSTRYWIND
select count(*) from wind.CBONDPLATEWIND
select count(*) from wind.CBONDISSUER
select count(*) from wind.COMPINTRODUCTION
select count(*) from wind.HKINDEXDESCRIPTION
select count(*) from wind.CBONDSPECIALCONDITIONS
select count(*) from wind.CBONDCF
select count(*) from wind.CBINDEXDESCRIPTION
select count(*) from wind.CHINAMUTUALFUNDDESCRIPTION
select count(*) from wind.CHINAOPTIONDESCRIPTION