select max(trade_dt) from wind.ASHAREEODPRICES  
select max(trade_dt) from wind.ASHAREEODDERIVATIVEINDICATOR  
select max(trade_dt) from wind.AINDEXEODPRICES  
select max(trade_dt) from wind.AINDEXCSI500WEIGHT  
select max(trade_dt) from wind.AINDEXHS300WEIGHT  
select max(trade_dt) from wind.CFUTURESMARGINRATIO  
select max(trade_dt) from wind.HS300IEODPRICES  
select max(FINANCIAL_TRADE_DT) from wind.HKSHAREEODDERIVATIVEINDEX 
select max(ACU_DATE) from wind.CBONDNEGATIVECREDITEVENT 
select max(trade_dt) from wind.CBONDVALUATION  
select max(trade_dt) from wind.HKSHAREEODPRICES  
select max(S_DQ_SUSPENDDATE) from wind.ASHARETRADINGSUSPENSION  
select max(trade_dt) from wind.CINDEXFUTURESEODPRICES  
select max(trade_dt) from wind.CBONDFUTURESEODPRICES  
select max(trade_dt) from wind.CCOMMODITYFUTURESEODPRICES  
select max(trade_dt) from wind.CBONDPRICES  
select max(trade_dt) from wind.HKSTOCKHSINDEXWEIGHT  
select max(trade_dt) from wind.HKINDEXEODPRICES  
select max(trade_dt) from wind.CBINDEXEODPRICES  
select max(trade_dt) from wind.COPTIONEMBEDDEDBONDVALUATION  
select max(PRICE_DATE) from wind.CHINAMUTUALFUNDNAV 
select max(trade_dt) from wind.CHINAOPTIONVALUATION  
select max(trade_dt) from wind.CBONDCURVECNBD  
select max(REPORT_PERIOD) from wind.ASHAREBALANCESHEET 
select max(REPORT_PERIOD) from wind.ASHARECASHFLOW   
select max(REPORT_PERIOD) from wind.ASHAREINCOME   
select max(REPORT_PERIOD) from wind.ASHAREFINANCIALINDICATOR   
select max(REPORT_PERIOD) from wind.ASHARETTMHIS   
select max(ENDDATE) from wind.HKCASHFLOWSIMPLE 
select max(REPORT_PERIOD) from wind.HKBALANCESHEETSIMPLE   
select max(ENDDATE) from wind.HKINCOMESIMPLE  
select max(ENDDATE) from wind.HKFINANCIALINDICATOR  
select max(ANN_DT) from wind.CBONDRATING 
select max(STARTDATE) from wind.CFUTURESCONTRACTMAPPING 
select max(trade_dt) from wind.CBONDISSUERRATING 


ASHAREEODPRICES TRADE_DT
ASHAREEODDERIVATIVEINDICATOR TRADE_DT
ASHAREBALANCESHEET REPORT_PERIOD
ASHAREINCOME REPORT_PERIOD
ASHARECASHFLOW REPORT_PERIOD
ASHAREFINANCIALINDICATOR REPORT_PERIOD
AINDEXEODPRICES TRADE_DT
ASHARETTMHIS REPORT_PERIOD
AINDEXCSI500WEIGHT TRADE_DT
AINDEXHS300WEIGHT TRADE_DT
CFUTURESMARGINRATIO TRADE_DT
HS300IEODPRICES TRADE_DT
HKBALANCESHEETSIMPLE REPORT_PERIOD
HKINCOMESIMPLE ENDDATE
HKCASHFLOWSIMPLE ENDDATE
HKFINANCIALINDICATOR ENDDATE
HKSHAREEODDERIVATIVEINDEX FINANCIAL_TRADE_DT
CBONDNEGATIVECREDITEVENT ACU_DATE
CBONDRATING ANN_DT
CBONDVALUATION TRADE_DT
HKSHAREEODPRICES TRADE_DT
ASHARETRADINGSUSPENSION S_DQ_SUSPENDDATE
CFUTURESCONTRACTMAPPING STARTDATE
CINDEXFUTURESEODPRICES TRADE_DT
CBONDFUTURESEODPRICES TRADE_DT
CCOMMODITYFUTURESEODPRICES TRADE_DT
CBONDPRICES TRADE_DT
HKSTOCKHSINDEXWEIGHT TRADE_DT
HKINDEXEODPRICES TRADE_DT
CBONDISSUERRATING ANN_DT
CBINDEXEODPRICES TRADE_DT
COPTIONEMBEDDEDBONDVALUATION TRADE_DT
CHINAMUTUALFUNDNAV PRICE_DATE
CHINAOPTIONVALUATION TRADE_DT
CBONDCURVECNBD TRADE_DT





