GET  https://fofinvesting.com/api/products/5e621b44b4c6b460c58d8ab7/analyze
authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJfaWQiOiI1ODdkYjQyZGRjNTkyZmYyMjdhNTQ4MWUiLCJlbWFpbCI6Imx1b3htQGNoaW5hcmUuY29tLmNuIiwidXNlcm5hbWUiOiJsdW94bSIsImNvbXBhbnkiOiLkuK3lm73lho3kv53pmanvvIjpm4blm6LvvInogqHku73mnInpmZDlhazlj7giLCJhdXRob3JpdGllcyI6W10sImluZHVzdHJpZXMiOltdLCJpYXQiOjE2MTU4ODIxODQsImV4cCI6MTYxNTk2ODU4NH0.HgbhnRX7PzJr4KA7v456fGkuIafWvt_DtWjQ1bEr_yg
Cache-Control: no-cache
Connection: keep-alive
Cookie: connect.sid=s%3AlpNLKx4yJ7-xuEMuj6aoghRYGvvPUGYB.W3P5SbJaBR6Em9L76NMcf6%2F2%2BAPzYV99LBi3CbJB0Ic; token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJfaWQiOiI1ODdkYjQyZGRjNTkyZmYyMjdhNTQ4MWUiLCJlbWFpbCI6Imx1b3htQGNoaW5hcmUuY29tLmNuIiwidXNlcm5hbWUiOiJsdW94bSIsImNvbXBhbnkiOiLkuK3lm73lho3kv53pmanvvIjpm4blm6LvvInogqHku73mnInpmZDlhazlj7giLCJhdXRob3JpdGllcyI6W10sImluZHVzdHJpZXMiOltdLCJpYXQiOjE2MTU4ODIxODQsImV4cCI6MTYxNTk2ODU4NH0.HgbhnRX7PzJr4KA7v456fGkuIafWvt_DtWjQ1bEr_yg